### ISSUE TITLE
Vind ik niet leuk

### ISSUE THREAD

**Issue by Knakiri** [DaXcess/SeroXen-Removal-Tool#1]
Hallo ik vind het niet leuk dat je een remover plaats voor seroxen

**Comment by DaXcess** [comment]
![crying-emoji-banging](https://github.com/DaXcess/SeroXen-Removal-Tool/assets/46288749/d8c7f84b-ce73-487f-b5f0-2a2dedce09a8)

**Comment by DaXcess** [comment]
Het wordt alleen nog maar leuker
![image](https://github.com/DaXcess/SeroXen-Removal-Tool/assets/46288749/f4d42731-5352-47e7-afa2-34340ba8376f)

**Comment by Knakiri** [comment]
Ja het gaat ook leuk worden als ik mijn rat af heb in mei ;)

**Comment by DaXcess** [comment]
mega cool en epic en supervet
